sudo: false

language: node_js

node_js:
  - "4"
  - "5"
  - "6"

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
    packages:
      - xvfb

install:
  - export CXX="g++-4.8"
  - npm install

script:
  - npm run pretest
  - npm run testA
